version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: $name$
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
