spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/$name$
    username: username
    password: password

server:
  compression:
    enabled: true
