name: Check
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: 'amazon-corretto@1.17.0-0.35.1'
      - name: Scripted
        run: sbt g8Test
